#!/usr/bin/env python
# vim: set syntax=python

import argparse
import os

import common
project = common.import_from_path( 'project', 'sts_project.py' )


parser = argparse.ArgumentParser(
        description = 'Create source directory.',
        formatter_class = argparse.ArgumentDefaultsHelpFormatter )
parser.add_argument( 'name', help = 'directory name' )

args = parser.parse_args()


# construct full paths and make header and source directories
dirs = [ os.path.join( project.include_dir, args.name ),
        os.path.join( project.src_dir, args.name ) ]

common.makedirs( dirs )
