#!/usr/bin/env python
# vim: set syntax=python

import argparse
import os

import common
project = common.import_from_path( 'project', 'sts_project.py' )


parser = argparse.ArgumentParser(
        description = 'Create header file.',
        formatter_class = argparse.ArgumentDefaultsHelpFormatter )
parser.add_argument( 'name', help = 'header name (e.g. [dirA/dirB/]MyHeader)' )
parser.add_argument( '--namespace', '--ns', help = 'namespace', default = project.default_namespace )

args = parser.parse_args()


# create header file from templates
include_file = os.path.join( project.include_dir, args.name + '.h' )

if os.path.exists( include_file ):
    print( 'Cannot create header. Existing file: ' + include_file )
else:
    common.create_file_from_template(
            include_file,
            common.template_path( 'cpp_header.h' ),
            {
                'namespace' : args.namespace
            } )
