#!/usr/bin/env python
# vim: set syntax=python

import argparse
import os

import common
project = common.import_from_path( 'project', 'sts_project.py' )


parser = argparse.ArgumentParser(
        description = 'Create source file.',
        formatter_class = argparse.ArgumentDefaultsHelpFormatter )
parser.add_argument( 'name', help = 'file name (e.g. [dirA/dirB/]MyHeader)' )
parser.add_argument( '--namespace', '--ns', help = 'namespace', default = project.default_namespace )

args = parser.parse_args()


# create header file from templates
src_file = os.path.join( project.src_dir, args.name + '.cpp' )

if os.path.exists( src_file ):
    print( 'Cannot create source file. Existing file: ' + src_file )
else:
    common.create_file_from_template(
            src_file,
            common.template_path( 'cpp_source.cpp' ),
            {
                'namespace' : args.namespace
            } )
