#!/usr/bin/env python
# vim: set syntax=python

import argparse
import sys
import os

import common


parser = argparse.ArgumentParser( description = 'Execute one of the project commands.' )
parser.add_argument( 'cmd', help = 'command (init/create_dir/create_class/...)' )
parser.add_argument( 'args', help = 'command arguments', nargs='*', default = [] )

args = parser.parse_args()

# insert sys.argv[ 0 ]
args.args.insert( 0, sys.argv[ 0 ] )

# sanitize and execute command
path = common.script_path( os.path.basename( args.cmd ) )

if os.path.isfile( path ) and os.access( path, os.X_OK ):
    os.execv( path, args.args )
else:
    print( 'Command does not exist.' )
